apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: goh6rwvnc-nodejs 
  janus-idp.io/tekton: goh6rwvnc-nodejs
  backstage.io/kubernetes-id: goh6rwvnc-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: goh6rwvnc-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml